server:
  port: 7080

spring:
  datasource:
    url: jdbc:mysql://47.120.64.211:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: o#DwN&JSa56
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml

netty:
  port: 8088
